# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice
service: buefy-shop-serverless

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# Configuration variables
custom:
  secrets: ${file(secrets.json)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    STRIPE_SECRET_KEY: ${self:custom.secrets.stripeSecretKey}

# The `functions` block defines what code to deploy
functions:
  createCharge:
    handler: functions/createCharge/createCharge.handler
    # The `events` block defines how to trigger the handler.createCharge code
    events:
      - http:
          path: charges
          method: post
          cors: true
